// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async getConfig() : Promise<Config> {
    return await TAURI_INVOKE("get_config");
},
async saveConfig(config: Config) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async login(username: string, password: string) : Promise<Result<GetUserProfileRespData, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login", { username, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async search(keyword: string, page: number, sort: SearchSort, year: number | null, month: number | null) : Promise<Result<SearchResultVariant, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search", { keyword, page, sort, year, month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 官方分类树 + 常用标签分组
 */
async getCategories() : Promise<Result<CategoryResp, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 对官方 API 线路做轻量测速，按延迟排序（失败的在最后）
 */
async probeApiLines() : Promise<Result<ApiLineProbeResult[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_api_lines") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 对图片线路做轻量测速（图片 CDN 没有可用性接口，这里只测连通性和延迟）
 */
async probeImageLines() : Promise<Result<ImageLineProbeResult[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_image_lines") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 当前正在使用的图片线路（失败会自动切换）
 */
async getActiveImageDomain() : Promise<string> {
    return await TAURI_INVOKE("get_active_image_domain");
},
async getComic(aid: number) : Promise<Result<Comic, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_comic", { aid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFavoriteFolder(folderId: number, page: number, sort: FavoriteSort) : Promise<Result<GetFavoriteResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_favorite_folder", { folderId, page, sort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllFavoriteComics(folderId: number, sort: FavoriteSort) : Promise<Result<ComicInFavorite[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_favorite_comics", { folderId, sort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWeeklyInfo() : Promise<Result<GetWeeklyInfoRespData, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_weekly_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWeekly(categoryId: string, typeId: string) : Promise<Result<GetWeeklyResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_weekly", { categoryId, typeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUserProfile() : Promise<Result<GetUserProfileRespData, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_user_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDownloadTask(comic: Comic, chapterId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_download_task", { comic, chapterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDownloadTasks(comic: Comic, chapterIds: number[]) : Promise<void> {
    await TAURI_INVOKE("create_download_tasks", { comic, chapterIds });
},
async pauseDownloadTask(chapterId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_download_task", { chapterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeDownloadTask(chapterId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_download_task", { chapterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDownloadTask(chapterId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_download_task", { chapterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadComic(aid: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_comic", { aid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadAllFavorites() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_all_favorites") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDownloadedComics() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_downloaded_comics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showPathInFileManager(path: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_path_in_file_manager", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncFavoriteFolder() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_favorite_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openComicReader(comic: Comic) : Promise<Result<ReaderComic, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_comic_reader", { comic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 按漫画ID打开阅读器：本地有就读本地，没有就走在线阅读
 */
async openReaderById(comicId: number) : Promise<Result<ReaderComic, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_reader_by_id", { comicId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 准备在线章节（请求图片地址），返回页数
 */
async prepareReaderChapter(token: number) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prepare_reader_chapter", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeReader() : Promise<void> {
    await TAURI_INVOKE("close_reader");
},
/**
 * 读取本地库存
 * - `source` 由前端显式传入，而不是从后端配置里读：切换「下载目录/导出目录」时，
 * 前端会同时发起 `save_config` 和这个命令，如果在这里读配置就会和写配置竞争，
 * 经常读到旧的来源，表现为「点了没切换，再点一次才行」
 */
async getLocalComics(source: LocalLibrarySource) : Promise<Comic[]> {
    return await TAURI_INVOKE("get_local_comics", { source });
},
/**
 * 本地库存的标签统计（标签云用）
 * - 只回「标签 + 次数」，前端不用把整库漫画都拉下来
 */
async getLocalTags(source: LocalLibrarySource) : Promise<LocalTag[]> {
    return await TAURI_INVOKE("get_local_tags", { source });
},
async getDownloadedComics() : Promise<Comic[]> {
    return await TAURI_INVOKE("get_downloaded_comics");
},
async exportCbz(comic: Comic) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_cbz", { comic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportCbzWithoutDownload(comicIds: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_cbz_without_download", { comicIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出某个目录里可以导出进快速阅读器的漫画（给前端勾选）
 */
async listQuickReaderCandidates(source: LocalLibrarySource) : Promise<Result<QuickReaderCandidate[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_quick_reader_candidates", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导出一份可以在浏览器里直接打开的快速阅读器（分享包）
 * - source = 从哪个目录收集漫画（导出目录 / 下载目录）
 * - keys = 选中的漫画（相对来源目录的路径）；为空表示全部
 * - dir_name = 阅读器文件夹名，重名会自动加 -2、-3 后缀
 * - target_dir = 写到哪个目录（绝对路径）；为空则写到来源目录
 */
async exportQuickReader(source: LocalLibrarySource, keys: string[], dirName: string | null, targetDir: string | null) : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_quick_reader", { source, keys, dirName, targetDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 导出「单文件 HTML」快速阅读器：图片以 base64 内嵌，一个文件就能读
 * - 手机浏览器禁止 file:// 页面读取子目录图片，只有内嵌才能在手机上直接打开
 * - split_by_chapter = true 时每章一个文件
 */
async exportQuickReaderSingleFile(source: LocalLibrarySource, keys: string[], targetDir: string | null, splitByChapter: boolean) : Promise<Result<string[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_quick_reader_single_file", { source, keys, targetDir, splitByChapter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportPdf(comic: Comic) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_pdf", { comic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportCbzChapters(comic: Comic, chapterIds: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_cbz_chapters", { comic, chapterIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportPdfChapters(comic: Comic, chapterIds: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_pdf_chapters", { comic, chapterIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogsDirSize() : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_logs_dir_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 空间统计：下载目录 / 导出目录 / 日志目录的占用，以及可以清理的东西
 */
async getStorageStats() : Promise<Result<StorageStats, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_storage_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 清理下载残留（`.下载中-*`），返回释放的字节数
 */
async cleanStorageLeftovers() : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean_storage_leftovers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 清理快速阅读器分享包（只删带阅读器标识文件的目录），返回释放的字节数
 */
async cleanStorageQuickReaders(paths: string[]) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean_storage_quick_readers", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 清理旧日志（保留最近 24 小时内以及最新的一份），返回释放的字节数
 */
async cleanStorageLogs() : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean_storage_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除一本已下载漫画的目录（只删下载目录里的），返回释放的字节数
 */
async deleteLocalComic(comicId: number) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_local_comic", { comicId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSyncedComic(comic: Comic) : Promise<Result<Comic, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_synced_comic", { comic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSyncedComicInFavorite(comic: ComicInFavorite) : Promise<Result<ComicInFavorite, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_synced_comic_in_favorite", { comic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSyncedComicInSearch(comic: ComicInSearch) : Promise<Result<ComicInSearch, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_synced_comic_in_search", { comic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSyncedComicInWeekly(comic: ComicInWeekly) : Promise<Result<ComicInWeekly, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_synced_comic_in_weekly", { comic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogFile(path: string) : Promise<Result<LogMetadata[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
downloadAllFavoritesEvent: DownloadAllFavoritesEvent,
downloadEvent: DownloadEvent,
exportCbzEvent: ExportCbzEvent,
exportPdfEvent: ExportPdfEvent,
exportQuickReaderEvent: ExportQuickReaderEvent,
logEvent: LogEvent,
updateDownloadedComicsEvent: UpdateDownloadedComicsEvent
}>({
downloadAllFavoritesEvent: "download-all-favorites-event",
downloadEvent: "download-event",
exportCbzEvent: "export-cbz-event",
exportPdfEvent: "export-pdf-event",
exportQuickReaderEvent: "export-quick-reader-event",
logEvent: "log-event",
updateDownloadedComicsEvent: "update-downloaded-comics-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ApiDomainMode = "Domain1" | "Domain2" | "Domain3" | "Domain4" | "Domain5" | "Custom"
/**
 * API 线路测速结果
 */
export type ApiLineProbeResult = { 
/**
 * 线路名，例如「线路1」
 */
label: string; 
/**
 * 对应设置页的线路选项
 */
mode: ApiDomainMode; domain: string; ok: boolean; latencyMs: number | null; error: string | null }
export type Category = { id: string | null; title: string | null }
export type CategoryInWeeklyInfo = { id: string; title: string; time: string }
/**
 * 官方分类树里的一个主分类
 */
export type CategoryNode = { id: number; name: string; slug: string; 
/**
 * 该分类下的作品总数
 */
totalAlbums: number; subCategories: SubCategoryNode[] }
/**
 * /categories 的完整返回：分类树 + 常用标签分组
 */
export type CategoryResp = { categories: CategoryNode[]; blocks: TagBlock[] }
export type CategoryRespData = { id: string | null; title: string | null }
export type CategorySub = { id: string | null; title: string | null }
export type CategorySubRespData = { id: string | null; title: string | null }
export type ChapterInfo = { chapterId: number; chapterTitle: string; order: number; 
/**
 * 是否曾导出过 PDF
 */
isPdfExported: boolean; 
/**
 * 是否曾导出过 CBZ
 */
isCbzExported: boolean; isDownloaded?: boolean | null; chapterDownloadDir?: string | null }
export type Comic = { id: number; name: string; addtime: string; description: string; total_views: string; likes: string; chapterInfos: ChapterInfo[]; series_id: string; comment_total: string; author: string[]; tags: string[]; works: string[]; actors: string[]; related_list: RelatedListRespData[]; liked: boolean; is_favorite: boolean; is_aids: boolean; isDownloaded?: boolean | null; comicDownloadDir?: string | null }
export type ComicInFavorite = { id: number; author: string; description: string | null; name: string; latestEp: string | null; latestEpAid: string | null; image: string; category: CategoryRespData; categorySub: CategorySubRespData; isDownloaded: boolean; comicDownloadDir: string }
export type ComicInSearch = { id: number; author: string; name: string; image: string; category: CategoryRespData; categorySub: CategorySubRespData; liked: boolean; isFavorite: boolean; updateAt: number; isDownloaded: boolean; comicDownloadDir: string }
export type ComicInWeekly = { id: number; author: string; description: string; name: string; image: string; category: Category; category_sub: CategorySub; liked: boolean; is_favorite: boolean; update_at: number; is_downloaded: boolean; comic_download_dir: string }
export type CommandError = { err_title: string; message: string }
export type Config = { username: string; password: string; downloadDir: string; exportDir: string; downloadFormat: DownloadFormat; dirFmt: string; proxyMode: ProxyMode; proxyHost: string; proxyPort: number; enableFileLogger: boolean; chapterConcurrency: number; chapterDownloadIntervalSec: number; imgConcurrency: number; imgDownloadIntervalSec: number; downloadAllFavoritesIntervalSec: number; updateDownloadedComicsIntervalSec: number; apiDomainMode: ApiDomainMode; customApiDomain: string; shouldDownloadCover: boolean; createPdfConcurrency: number; enableMergePdf: boolean; 
/**
 * 导出跳过模式
 */
exportSkipMode: ExportSkipMode }
export type DownloadAllFavoritesEvent = { event: "GetFavoritesStart" } | { event: "GetComicsProgress"; data: { current: number; total: number } } | { event: "StartCreateDownloadTasks"; data: { comicId: number; comicTitle: string; current: number; total: number } } | { event: "CreatingDownloadTask"; data: { comicId: number; current: number } } | { event: "EndCreateDownloadTasks"; data: { comicId: number } } | { event: "GetComicsEnd" }
export type DownloadEvent = { event: "Speed"; data: { speed: string } } | { event: "Sleeping"; data: { chapterId: number; remainingSec: number } } | { event: "TaskCreate"; data: { state: DownloadTaskState; comic: Comic; chapterInfo: ChapterInfo; downloadedImgCount: number; totalImgCount: number } } | { event: "TaskDelete"; data: { chapterId: number } } | { event: "TaskUpdate"; data: { chapterId: number; state: DownloadTaskState; downloadedImgCount: number; totalImgCount: number } }
export type DownloadFormat = "Jpeg" | "Png" | "Webp"
export type DownloadTaskState = "Pending" | "Downloading" | "Paused" | "Completed" | "Failed"
export type ExportCbzEvent = { event: "Start"; data: { uuid: string; comicTitle: string; total: number } } | { event: "Progress"; data: { uuid: string; 
/**
 * 已完成的章节数
 */
current: number; 
/**
 * 当前章节已下载的图片数（仅直接导出时会上报）
 */
imgCurrent: number | null; 
/**
 * 当前章节的图片总数（仅直接导出时会上报）
 */
imgTotal: number | null; 
/**
 * 当前正在处理的章节标题（仅直接导出时会上报）
 */
chapterTitle: string | null } } | { event: "Error"; data: { uuid: string } } | { event: "End"; data: { uuid: string; comicId: number; chapterExportDir: string } }
export type ExportPdfEvent = { event: "CreateStart"; data: { uuid: string; comicTitle: string; total: number } } | { event: "CreateProgress"; data: { uuid: string; current: number } } | { event: "CreateError"; data: { uuid: string } } | { event: "CreateEnd"; data: { uuid: string; comicId: number; chapterExportDir: string } } | { event: "MergeStart"; data: { uuid: string; comicTitle: string; total: number } } | { event: "MergeProgress"; data: { uuid: string; current: number } } | { event: "MergeError"; data: { uuid: string } } | { event: "MergeEnd"; data: { uuid: string; comicId: number; chapterExportDir: string } }
export type ExportQuickReaderEvent = { event: "Start"; data: { total: number } } | { event: "Progress"; data: { current: number; total: number; indicator: string } } | { event: "End"; data: { dir: string } } | { event: "Error"; data: { message: string } }
/**
 * 导出跳过模式
 */
export type ExportSkipMode = 
/**
 * 每次重新导出所有章节
 */
"None" | 
/**
 * 跳过本地已存在的导出文件
 */
"SkipExisting" | 
/**
 * 跳过曾导出过的章节（即使本地文件已删除）
 */
"SkipExported"
export type FavoriteFolderRespData = { FID: string; UID: string; name: string }
export type FavoriteSort = "FavoriteTime" | "UpdateTime"
export type GetFavoriteResult = { list: ComicInFavorite[]; folderList: FavoriteFolderRespData[]; total: number; count: number }
export type GetUserProfileRespData = { uid: string; username: string; email: string; emailverified: string; photo: string; fname: string; gender: string; message: string | null; coin: number; album_favorites: number; s: string; level_name: string; level: number; nextLevelExp: number; exp: string; expPercent: number; album_favorites_max: number; ad_free: boolean; charge: string; jar: string; invitation_qrcode: string; invitation_url: string; invited_cnt: string }
export type GetWeeklyInfoRespData = { categories: CategoryInWeeklyInfo[]; type: WeeklyType[] }
export type GetWeeklyResult = { total: number; list: ComicInWeekly[] }
/**
 * 图片线路测速结果
 */
export type ImageLineProbeResult = { domain: string; ok: boolean; latencyMs: number | null; error: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue }
/**
 * 本地库存读取的目录
 * - 注意：这只是"看哪个目录"的视图偏好，由前端存在 localStorage 里，
 * 不再是 Config 的一部分（切一下目录不该触发保存配置）
 */
export type LocalLibrarySource = 
/**
 * 下载目录（正常下载的漫画）
 */
"DownloadDir" | 
/**
 * 导出目录（只导出过 cbz、没有下载过的漫画）
 */
"ExportDir"
/**
 * 标签 + 出现次数（"我的口味"标签云用）
 */
export type LocalTag = { name: string; count: number }
export type LogEvent = { jsonRaw: string }
export type LogLevel = "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR"
export type LogMetadata = { timestamp: string; level: LogLevel; fields: { [key in string]: JsonValue }; target: string; filename: string; line_number: number; span?: JsonValue; spans?: LogSpan[] }
export type LogSpan = ({ [key in string]: null | boolean | number | string | JsonValue[] | { [key in string]: JsonValue } }) & { name: string }
export type ProxyMode = "System" | "NoProxy" | "Custom"
/**
 * 可以导出进阅读器的漫画（给前端勾选用）
 */
export type QuickReaderCandidate = { 
/**
 * 相对来源目录的路径，导出时回传
 */
key: string; 
/**
 * 展示用的漫画名（目录名）
 */
name: string; chapterCount: number; pageCount: number; 
/**
 * 估算体积（字节），用于提示单文件会不会太大
 */
estimatedBytes: number; 
/**
 * 图片来源：图片目录 / cbz
 */
kind: string }
export type ReaderChapter = { 
/**
 * 传给自定义协议用的章节令牌
 */
token: number; title: string; 
/**
 * 在线章节在打开前还不知道页数（是0），需要先调用 prepare_reader_chapter
 */
pageCount: number; 
/**
 * 是否是在线章节
 */
online: boolean }
export type ReaderComic = { title: string; chapters: ReaderChapter[] }
export type RelatedListRespData = { id: string; author: string; name: string; image: string }
export type SearchResult = { searchQuery: string; total: number; content: ComicInSearch[] }
export type SearchResultVariant = { SearchResult: SearchResult } | { Comic: Comic }
export type SearchSort = "Latest" | "View" | "Picture" | "Like"
/**
 * 某个目录的占用情况
 */
export type SizeStat = { path: string; bytes: number; 
/**
 * 漫画数（日志目录里是日志文件数）
 */
count: number }
/**
 * 一条可以清理/查看的记录
 */
export type StorageEntry = { name: string; path: string; bytes: number; 
/**
 * 漫画ID（只有"占用最大的漫画"有）
 */
comicId: number | null }
export type StorageStats = { download: SizeStat; export: SizeStat; logs: SizeStat; 
/**
 * 快速阅读器分享包（下载目录 + 导出目录里的）
 */
quickReaders: StorageEntry[]; 
/**
 * 下载残留的临时目录
 */
leftovers: StorageEntry[]; 
/**
 * 占用最大的几本漫画
 */
biggestComics: StorageEntry[] }
/**
 * 分类树里的子分类
 */
export type SubCategoryNode = { cid: number; name: string; slug: string }
/**
 * 官方「常用标签」分组（/categories 的 blocks 字段）
 */
export type TagBlock = { title: string; content: string[] }
export type UpdateDownloadedComicsEvent = { event: "GetComicStart"; data: { total: number } } | { event: "GetComicProgress"; data: { current: number; total: number } } | { event: "CreateDownloadTasksStart"; data: { comicId: number; comicTitle: string; current: number; total: number } } | { event: "CreateDownloadTaskProgress"; data: { comicId: number; current: number } } | { event: "CreateDownloadTasksEnd"; data: { comicId: number } } | { event: "GetComicEnd" }
export type WeeklyType = { id: string; title: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
